query ProductDetail($id: ID!, $first: Int = 10, $after: String, $before: String, $last: Int) {
	product(id: $id) {
		id
		title
		description
		slug
		status
		priceRange {
			start {
				amount
				currency
			}
			stop {
				amount
				currency
			}
		}
		category {
			id
			title
		}
		createdAt
		updatedAt
		variants(first: $first, after: $after, before: $before, last: $last) {
			edges {
				node {
					id
					sku
					title
					price {
						amount
						currency
					}
					createdAt
					updatedAt
				}
			}
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
			}
		}
	}
}
