query Products {
	products(first: 5) {
		edges {
			node {
				id
				title
				description
				createdAt
				updatedAt
				category {
					title
				}
				status
				priceRange {
					start {
						amount
					}
					stop {
						amount
					}
				}
			}
		}
	}
}
