query Products($first: Int = 10, $query: String, $after: String, $before: String, $last: Int, $orderBy: [ProductOrderField], $orderDirection: OrderDirection) {
	products(first: $first, query: $query, after: $after, before: $before, last: $last, orderBy: $orderBy, orderDirection: $orderDirection) {
		edges {
			node {
				id
				title
				description
				status
				createdAt
				updatedAt
				category {
					title
				}
				priceRange {
					start {
						amount
						currency
					}
					stop {
						amount
						currency
					}
				}
			}
		}
		pageInfo {
			hasNextPage
			hasPreviousPage
			startCursor
			endCursor
		}
	}
	categories(first: 50) {
		edges {
			node {
				id
				title
				slug
			}
		}
	}
}
