name: "simple-commerce"

services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: simple_commerce
      POSTGRES_USER: simple_commerce
      POSTGRES_PASSWORD: simple_commerce
    ports:
      - "5432"