name: "simple-commerce"

services:
  simple_commerce:
    image: juliuskrah/simple-commerce
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/simple_commerce
      SPRING_DATASOURCE_USERNAME: simple_commerce
      SPRING_DATASOURCE_PASSWORD: simple_commerce
      MINIO_ENDPOINT: http://objectStore:9000
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://oidc:5556/dex/keys
      SPRING_PROFILES_ACTIVE: oidc-authn, keto-authz
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      objectStore:
        condition: service_started
    profiles:
      - app
  postgres:
    image: postgres:17.2-alpine
    hostname: postgres
    environment:
      POSTGRES_DB: simple_commerce
      POSTGRES_USER: simple_commerce
      POSTGRES_PASSWORD: simple_commerce
    volumes:
      - ./postgresql/init-dex-db.sh:/docker-entrypoint-initdb.d/init-dex-db.sh
    ports:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "dex"]
      interval: 10s
      timeout: 5s
      retries: 3
  objectStore:
    image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z-cpuv1
    command: ["server", "--console-address", ":9001"]
    environment:
      MINIO_CONFIG_ENV_FILE: /etc/config.env
      MINIO_ROOT_USER: simple_commerce
      MINIO_ROOT_PASSWORD: simple_commerce
    volumes:
      - objectStoreData:/mnt/data
      - ./minio/config:/etc/config.env
    ports:
      - "9001:9001"
      - "9000:9000"
    labels:
      com.simplecommerce.endpoint.scheme: http
  oidc:
    image: ghcr.io/dexidp/dex:v2.41.1-distroless
    command: ["dex", "serve", "/etc/dex.yaml"]
    volumes:
      - ./dex/config.yaml:/etc/dex.yaml
    ports:
      - "5556:5556"
      - "5557:5557"
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - oidc-authn
  keto:
    image: oryd/keto:v0.12.0-distroless
    command: ["serve", "--config", "/home/ory/keto.yaml"]
    volumes:
      - ./keto/keto.yaml:/home/ory/keto.yaml
      - ./keto/namespaces.keto.ts:/home/ory/namespaces/namespaces.keto.ts
    ports:
      - "4466:4466"
      - "4467:4467"
      - "4469:4469"
    depends_on:
      keto-migrate:
        condition: service_completed_successfully
    profiles:
      - keto-authz
  keto-migrate:
    image: oryd/keto:v0.12.0-distroless
    command: ["migrate", "up", "--format", "table", "--yes", "--config", "/home/ory/keto.yaml"]
    volumes:
      - ./keto/keto.yaml:/home/ory/keto.yaml
      - ./keto/namespaces.keto.ts:/home/ory/namespaces/namespaces.keto.ts
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - keto-authz

volumes:
  objectStoreData:
    driver: local
