management:
  endpoint:
    env:
      access: unrestricted
      show-values: always
    auditevents:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include:
        - auditevents
        - metrics
        - health
        - env
        - info
        - beans
        - sbom
        - mappings
